/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RDGFontsAndIcons
///      fonts:
///       - asset: fonts/RDGFontsAndIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RDGFontsAndIcons {
  RDGFontsAndIcons._();

  static const _kFontFam = 'RDGFontsAndIcons';
  static const _kFontPkg = null;

  static const IconData GoogleG = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
